import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import NavBar from "@/src/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rick & Morty WiKi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="bg-blue-500 flex justify-between items-center">
          <Link href={'/'} className="text-white text-3xl font-bold mx-4">Rick & Morty Wiki</Link>
          <NavBar />
        </header>

        <main className="flex flex-grow justify-center">
          {children}
        </main>

        <footer 
          className="
            h-20 bg-blue-500 
            flex flex-col
            justify-center items-center 
            text-white
          ">
            <div>
              My project 2026
            </div>

            <div className="font-semibold hover:-translate-y-1">
              <Link href={'https://github.com/andriiLink/rick-morty'}>{'>>>'}GitHub repository{'<<<'}</Link>
            </div>
          </footer>
      </body>
    </html>
  );
}


// className="flex flex-grow"
//truncate
